---
# This playbook will be run on openvpn nodes.

- name: Get gpg key for OpenVPN repository
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present

- name: Add OpenVPN repository into sources list
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main
    state: present

- name: Install OpenVPN
  apt: name=openvpn state=present update_cache=yes
  tags: vpn

- name: Install Easy RSA
  apt: name=easy-rsa state=present
  tags: easyRSA

- name: Certificate Authority Directory
  command: make-cadir /etc/openvpn/easy-rsa
  args:
    creates: /etc/openvpn/easy-rsa

- name: Adjust environment variables
  template:
    src: vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: Build Certificate Authority (CA)
  shell: . ./vars && ./clean-all && ./build-ca --batch
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: keys/ca.key

- name: Generate a certificate and private key for the server
  shell: . ./vars && ./pkitool --batch --server {{ ServerName }}
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: keys/{{ ServerName }}.key

- name: Build Diffie-Hellman parameters for the server side
  shell: . ./vars && ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: keys/dh2048.pem

- name: copy server keys to /etc/openvpn
  copy:
    remote_src: True
    src: /etc/openvpn/easy-rsa/keys/{{ item }}
    dest: /etc/openvpn/
    owner: root
    group: root
    mode: 0600
  with_items:
    - "{{ ServerName }}.crt"
    - "{{ ServerName }}.key"
    - ca.crt
    - dh2048.pem

- name: Server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: restart openvpn

- name: Make sure OpenVPN is started
  systemd:
    name: openvpn@server
    state: started
    enabled: yes
